### ISSUE TITLE
Webpack | Use yarn to download dependencies and webpack to bundle them

### ISSUE THREAD

**Issue by jfmdev** [AdvancedThreatAnalytics/threat-analytics-search#1]
Currently we have a `libs/` folder where we manually put all dependencies need by the extension, but it would be better to use Yarn to download them, since having all dependencies defined in `package.json` will simplify detecting when a dependency became outdated and to upgrade them.

Requirements:

- [ ] Remove the `libs/` folder and install all dependencies declared using Yarn.
- [ ] Update the `.gitinore` file so the `node_modules/` folder is ignored.
- [ ] Use Webpack to manage dependencies, so instead of using `loadScript(...)` (on `background.js`) `<script src="...">` / `<link href=""` tags (on HTML files) we just use the ~require()~ `import` command on JavaScript files.
- [ ]  Check that `yarn run build` works correctly.
- [ ] Implement a new `yarn run live` command that will watch for any change on the files from the `src/` folder and run the `build` script every time a file is modified. This command will be helpful for when developing the extension.

Reference: https://webpack.js.org/guides/getting-started/

Blocked by AdvancedThreatAnalytics/threat-analytics-search-deprecated#9

**Comment by Saidmurod1996** [comment]
Reopened due to bootstrap being version 5 instead of version 4
