### ISSUE TITLE
Options | Gray the text of disabled groups instead of using a line though

### ISSUE THREAD

**Issue by jfmdev** [AdvancedThreatAnalytics/threat-analytics-search#12]
On the forms to edit Search Providers we are putting a line though to groups that aren't enabled, however this has proved to be confusing to users. Instead of putting a line though we should perhaps show make the text gray, instead of black (i.e. use `.text-muted` instead of `.text-line-through`).

**Comment by pushpendraKh** [comment]
@jfmdev If the group is disabled, shouldn't the checkbox also disabled?

**Comment by jfmdev** [comment]
@pushpendraKh No, users may want to add/remove an item to the group, and then enable the group.
