### ISSUE TITLE
Publish 5.1 to Chrome Web Extension App Store

### ISSUE THREAD

**Issue by cs-shadowbq** [AdvancedThreatAnalytics/threat-analytics-search#122]
Publishing a zip file is not good enough for most people to utilize an extension.

Please publish the full crx to the chrome webstore 

Current WebStore:

Version
5.0.3
Updated
May 13, 2021
Size
1.47MiB

**Comment by jfmdev** [comment]
@cs-shadowbq Thanks for interest and sorry for they delay: we are hopping to deploying version v5.1 between this and next week

**Comment by jfmdev** [comment]
@cs-shadowbq Version 5.1.1 is available to download!

> https://chrome.google.com/webstore/detail/threat-analytics-search/eliokoocofjemjjohafbmhmgjmedomko
