### ISSUE TITLE
Settings | search providers are outdated in settings.json

### ISSUE THREAD

**Issue by Saidmurod1996** [AdvancedThreatAnalytics/threat-analytics-search#132]
In settings.json the searchproviders link is different (outdated) than the providers inside `update` field (introduced by this [PR](https://github.com/AdvancedThreatAnalytics/threat-analytics-search/pull/53)) That is causing a bug Pushpendra mentioned [here](https://github.com/AdvancedThreatAnalytics/threat-analytics-search/pull/131#issuecomment-986745792). Searchproviders link in settings.json file should be changed to new ones.

**Comment by pushpendraKh** [comment]
@Saidmurod1996 I don't think it's a bug. It was the enhancement that we did to search providers without duplicating entries in search provider (this was done before we introduce the Merge Setting option, AFAIR).

 Checkout https://github.com/AdvancedThreatAnalytics/threat-analytics-search/pull/53 PR's description and comments.
