### ISSUE TITLE
Settings | Importing settings from file ignores special providers

### ISSUE THREAD

**Issue by pushpendraKh** [AdvancedThreatAnalytics/threat-analytics-search#184]
There seems to be a problem with “Importing“ settings from a file. Is it is not overriding special providers (NWI, CBC, RSA) settings - just ignoring the changes for this. 

Note that it works fine for Context Menu items. Context Menu items are getting overridden from imported files.

**Expected Behavior**
It should override everything - Context Menu items, NWI, CBC and RSA.

**Comment by jfmdev** [comment]
This is _probably_ related to the `forceOverride` parameter from the `ConfigFile.updateSpecialProvider` function.
