### ISSUE TITLE
Settings | Fix branding for third party vendors

### ISSUE THREAD

**Issue by vnagendra** [AdvancedThreatAnalytics/threat-analytics-search#22]
Our default configuration includes a fair number of third party vendors. They have changed names (and other branding items) in many cases. We should reflect the vendor's latest branding.

**Comment by jfmdev** [comment]
Requirements

- [ ] Test every entry on `settings.json` and check if:
    - The vendor hasn't changed his name (e.g. on the JSON the label might be "Defender" but when you go to the site the vender has updated his name to "Microsoft Defender")..
    - User isn't directed to a different URL (e.g. on the JSON the URL is `defender.com?q=SEARCH` but when you open it, using a valid value for SEARCH, the user it's redirected to `search.defender.com?q=SEARCH`).
