### ISSUE TITLE
Build | Prevent duplication (and reduce build size)

### ISSUE THREAD

**Issue by jfmdev** [AdvancedThreatAnalytics/threat-analytics-search#30]
Current entry files are very weighty, and that's probably because each one of them is having their own copies of Lodash, Mustache and other dependencies.

As indicated on [Webpack docs](https://webpack.js.org/guides/code-splitting/#prevent-duplication) we should prevent duplication of code. This will not only reduce the loading time of the Options page, but will also reduce the size of builds (~ 13 MB instead of ~ 16 MB).

**Comment by Saidmurod1996** [comment]
@jfmdev Sorry for not noticing it the first time in PR #31 , but now because of this change app is broken (neither context menu nor options page is shown).
