### ISSUE TITLE
Testing | Add framework for E2E testing

### ISSUE THREAD

**Issue by jfmdev** [AdvancedThreatAnalytics/threat-analytics-search#59]
Looks for a framework (and any required library) that will allow to perform E2E tests over the extension (preferability Cypress)

> Hints:
> 
> * https://docs.cypress.io/guides/tooling/plugins-guide#Browser-Launching
> * https://walrus.ai/blog/2021/02/simple-steps-for-testing-a-chrome-extension-in-puppeteer/

Requirements:

- [x] Search for a framework (and any additional library) that will allow to perform E2E tests in the extension.
- [x] Implement a simple E2E test for select a work on a page, open the context menu, and search it using the "Google" option.

Related to #57

**Comment by tim-kodirov** [comment]
I have chosen to use Puppeteer & Jest frameworks for e2e testing, as Cypress doesn't support protocols other than `http` and `https` (see [this](https://github.com/cypress-io/cypress/issues/298) thread for more information).

Also note that the requirement `Implement a simple E2E test for select a work on a page, open the context menu, and search it using the "Google" option.` can't be implemented as the context menu opened in chrome is not part of the actual DOM, hence it can't be accessed. So, instead, I added a test for checking if an option name in options pages is changed when typing another value
