### ISSUE TITLE
Options | Add additional options for update settings

### ISSUE THREAD

**Issue by jfmdev** [AdvancedThreatAnalytics/threat-analytics-search#6]
We should provide more options to user about how the `.json` files should be merged with current settings (currently the only thing users can do is to check if "Groups" names should be updated or not).

Requirements:

- [ ] Move the checkbox "Enable groups" (for `useGroups` option) to the "Search Results Options" column (since this option should exclusively be used for show/hide groups on the context menu, we should have a completely separate option to check if groups names should be updated when refreshing the settings).
- [ ] Rename the label "Last Refreshed on" to "Last Updated on".
- [ ] Rename the "Refresh now" button to "Update now".
- [ ] Rename the "Refresh automatically" label to "Update periodically (once per week)".
- [ ] Add a new title (with is own list of items) called "Merge Settings Options".
- [ ] One merge option should be a dropdown with values "Merge", "Override" and "Ignore" and a side label "Search Providers". Default value for the dropdown should be "merge".
- [ ] Next to the previous label should be a info icon that, when clicked, will open a popover explaining that with "Override" all local search providers will be deleted and replaced when settings are updated, that "Merge" will just add (to the current list of search providers) the search providers that aren't already added from the settings file, and that "Ignore" will keep current list and ignore anything on the settings file.
- [ ] Another merge option should be a checkbox called "Override Groups names" (defaulted to false). 
- [ ] Another merge option should be a checkbox with label "Override Carbon Black Configuration", defaulted to false.
- [ ] Another merge option should be a dropdown with values "Merge", "Override" and "Ignore" and a side label "Carbon Black Queries". Here we should also have a info icon similar to the one of "Search Providers".
- [ ] The finales merge options will be the same checkbox and dropdown from Carbon Black, but for Security Analytics and NetWitness.
- [ ] The values for these merge options should be should also be stored into the Chrome's storage, inside the object from `StoreKey.SETTINGS`, using the field names: `mergeSearchProviders`, `mergeGroups`, `mergeCBC`, `mergeRSA` and `mergeNWI` (these last three with fields `config` and `queries`).
- [ ] Optimize the implementation on `settings.html` use Mustache, by defining a template that will render the checkboxs, inputs and dropdowns (like currently done by the `template_providerConfig` template).
- [ ] On `utils.js` create constants `MERGE_OPTIONS`, `SEARCH_RESULT_OPTIONS` and `CONFIG_FILE_OPTIONS` for define arrays with the data which will be used to generate all inputs from the previous step.
- [ ] Update the `parseJSONFile` function so all these settings are keeping in mind when merging the a JSON file with current settings.
- [ ] Finally, on `migration.js` the value for "Override Groups names" should be initialized to the same value of `useGroups`.

> Please note that, for simplify code when update merge options for CBC / RSA / NWI, you can use the `_.set` and `_.get` methods from Lodash for doing things like `var mergeCBCConfig = _.get( await LocalStore.getOne(StoreKey.SETTINGS), "mergeCBC.config", {})` and `var settings = await LocalStore.getOne(StoreKey.SETTINGS); _.set(settings, "mergeCBC.config", newCBCConfigSettings)`.  
>
> This will also simplify how you define `MERGE_OPTIONS`, since you will be able to do something like:
>
> ```js
> var MERGE_OPTIONS = [
>    { storeKey: "mergeSearchProviders", label: "Search Providers", fields: [...], ... }
>    { storeKey: "mergeGroups", label: "Providers Groups", fields: [...], ... }
>    { storeKey: "mergeCBC.config", label: "Carbon Black Configuration", fields: [...], ... }
>    { storeKey: "mergeCBC.queries", label: "Carbon Black Queries", fields: [...], ... }
>   ...
> ];
> ```

**Comment by pushpendraKh** [comment]
@jfmdev Will this UI work? 

<img width="454" alt="config" src="https://user-images.githubusercontent.com/11942435/119103204-822f3980-ba38-11eb-9a88-3a9a393574b6.png">

**Comment by jfmdev** [comment]
@pushpendraKh Not quite... the "Merge Settings Options" should  be outside "Configuration File Options" (i.e. the "Merge Settings Options" text should be in a `<h1>` and his options should be in is own list).

> Also, the "Update now" button should be inside the "Last updated on" item (like it's now), otherwise gives the impression that clicking it will save the form (instead of re-fetching the configuration file).

**Comment by pushpendraKh** [comment]
Like this right?

<img width="360" alt="config" src="https://user-images.githubusercontent.com/11942435/119161806-57180a80-ba77-11eb-9686-51f7bb2c3819.png">
<img width="350" alt="merge" src="https://user-images.githubusercontent.com/11942435/119161829-5bdcbe80-ba77-11eb-9386-ae80b8917d20.png">

**Comment by jfmdev** [comment]
@pushpendraKh Yes, exactly 👍
